### ISSUE TITLE
Uptime errors not published to user

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-image#100]
The following uptime errors are being reported, but they are not being published to the User:

- E000000014

**Comment by stulees** [comment]
@alanclayton Is there any reason this should remain open?  @olegrise FYI

**Comment by alanclayton** [comment]
@stulees yeah, because the error isn't being published to the user.

**Comment by ezequielc** [comment]
@stulees Closing as per https://github.com/Rise-Vision/rise-twitter/issues/70#issuecomment-916420515. Please update the defects spreadsheet. Thanks!
