### ISSUE TITLE
Rise Image logging millions of error 27 logs for the same endpoint on the same day

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-image#103]
This query shows at least one endpoint logging the same E000000027 error hundreds of times per second.
 
```
select * from `endpoint-event-logs.logs.eventLog` where 
date(timestamp) = "2021-04-26"
and endpointId = "ac1ac885ec08b63284c7e10b33a14120"
order by timestamp desc
```

**Comment by stulees** [comment]
@tejohnso Sounds like a duplicate of #102 , I don't think we need two of them open. Can you take this defect description and just add as a comment to #102 ?

**Comment by tejohnso** [comment]
ok
