### ISSUE TITLE
Animated templates from Canva are converted to PNG and lose their animations

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-image#106]
### What is the expected behavior?
As a user, I can design an image using Canva.  If I pick one of Canva's templates, edit it, and save it, it's uploaded to Rise Vision Storage for me to use as I created it.

### What is the actual behavior?
As a user, if I start from one of Canva's animated templates, and make edits to it, but once I click Save the image is converted to PNG.  Since a PNG does not animate, the end result doesn't look like what it did in Canva.

### What steps can be taken to replicate the problem?
Here's a video demonstration: https://drive.google.com/file/d/1ys0i3IaBVJvWSuRoSac6EH2B2x8c0PdU/view?usp=drivesdk

**Comment by ezequielc** [comment]
@PatrickA-RiseVision I took a look at this and unfortunately this is a limitation of the Canva integration itself. I revised their documentation and it only allows us to get the image as png, jpg or pdf. 
Our only option here would be to reach Canva and request them to add more export options, like gif. Thanks
@alex-deaconu fyi

**Comment by ezequielc** [comment]
@PatrickA-RiseVision As per discussion in SoS, this is outside of our control, so we should add a note in the documentation about this limitation and watch if it becomes a common source of problems for users.
Closing the defect for now. Thanks!
