### ISSUE TITLE
"responsive" attribute does not act as expected

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-image#17]
Steps to Replicate:
Add an instance of the image component with the attribute "responsive" inside a parent div that has its size set to 100% or 100vw.
Branch: https://github.com/Rise-Vision/html-template-library/tree/fullscreen-image/build-beta/build/fullscreen-image

Expected behavior:
The image should scale to the size of its parent div containers width no matter what its size is. It should not scale out of aspect ratio and should center center.

Actual behavior: 
The image will scale to the parent divs size up to a certain point.  Once it reaches its native image size it stops scaling.

Video Overview: https://www.screencast.com/t/jc2RenKFTXN

Workaround: This is an issue for 4k screens only. However, I can write a media query that has a css scale3d property specifically for 4k. This workaround is not ideal because it's adaptive and not responsive. So it only accounts for specific resolutions I target vs any and everything.

**Comment by stulees** [comment]
Fixed with #19

**Comment by mmeiers** [comment]
The image component functions as intended with responsive attribute. The only exception is images do not scale past their native resolution. This is important for 4k screens.
My expected behavior is that: 

• The image scales to the width of the wrapper without going out of ratio or outside the wrapper.
• The image scales to the height of the wrapper without going out of ratio or outside the wrapper. 

Supporting video: https://www.screencast.com/t/VQPL0R9wZ
Note: I was able to position it how I wanted by targeting the rise-image ID. I just am not able to force it to size to the wrapper.

PR / Branch: 
https://github.com/Rise-Vision/html-template-library/pull/343

**Comment by stulees** [comment]
@mmeiers As per discussion on Trello card, closing this as it's been determined there is no defect. To achieve the results you were looking for required HTML/CSS in the template and no changes to the `rise-image` component. 

For reference, the branch I applied my experiment successfully for full screen image template is [here](https://github.com/Rise-Vision/html-template-library/tree/fullscreen-image/staging/responsive/fullscreen-image/src)

The branch @santiagonoguez applied his experiment successfully for your other example template situation is [here](https://github.com/Rise-Vision/html-template-library/commit/b0b657c0af8c933e1ad95033371c84d278072399)
