### ISSUE TITLE
Image is not refreshed if it is re uploaded (only happens in Preview)

### ISSUE THREAD

**Issue by fjvallarino** [Rise-Vision/rise-image#29]
Related to the thumbnails issue update that was fixed as part of https://github.com/Rise-Vision/rise-vision-apps/issues/1061, we should add an extra parameter to the image URL that references GCS' `timeCreated.value`. This is only needed for Preview, since RLS handles this correctly for the displays

**Comment by stulees** [comment]
@fjvallarino Curious, is this actually a `rise-image` defect, or a requirement of releasing https://github.com/Rise-Vision/rise-vision-apps/issues/1061 fix?

**Comment by fjvallarino** [comment]
@stulees we discussed with @santiagonoguez today during Stand Up. It's related, since users re uploading images will not see Preview's content updated, but it's not the same, since it's not the thumbnail what we're trying to load but the image itself (whose content is being updated correctly, even without the thumbnail fixes).

**Comment by santiagonoguez** [comment]
Fixed here: https://github.com/Rise-Vision/rise-image/pull/33

Closing.
