### ISSUE TITLE
Rise Image Element has an extra 2px added

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-image#53]
Reproduction Steps
1. Add an image component.
2. Add a box-shadow to either the id of the component or its parent container.
box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);

Expected Results
I would expect the drop shadow to start at the exact bottom of the image. 

Actual Results
The drop shadow is offset by 2 pixels. Dev console says that there is an extra 2px in the rise-image element, so for that one there it is 602px height but the image is 600px and the height set in the component attribute itself is 600px.
https://apps.risevision.com/templates/edit/9a4bff03-4769-426d-8199-cd5750388dd0/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

https://rise-vision-inc.slack.com/archives/CCDCUDRJQ/p1581367780017600

**Comment by stulees** [comment]
Fixed with #54 , @mmeiers FYI thanks!
