### ISSUE TITLE
Image Full Screen Template flashes white briefly before each image

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-image#60]
### What is the expected behavior?
Image slideshows play smoothly in the Image Full Screen template.  Images are replaced immediately with the next image in the slideshow.

### What is the actual behavior?
Intermittently there is a white flash before each image.  It's noticeable on a Pi 4 with 4GB RAM when it's the only presentation in the schedule.  Sometimes it behaves as expected for a little while, and then starts flashing again.

I can also replicate this on my Linux NUC, but it's barely noticeable without really looking for it (maybe 2 frames at most).

### What steps can be taken to replicate the problem?
- Create a presentation from the Image Full Screen template
- Upload images to the template.  I don't think size or number matter, but I used 15 images in my test.
- Schedule it to play on a Pi.

Cheers,

**Comment by stulees** [comment]
Not pursuing this now.
