### ISSUE TITLE
Image component plays default image immediately before presentations are swapped

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-image#84]
### What is the expected behavior?
When I add images to a Template, they replace the default image and the default image is no longer visible.

### What is the actual behavior?
Specifically in Financial templates, it looks like the content is unloaded a split second before the presentation changes to the next one in the schedule playlist and the defaults are visible, causing a jarring flash.

https://drive.google.com/file/d/1rZQCGWvi3IexZSBVWlO8bJML8I69--ao/view?usp=sharing

### What steps can be taken to replicate the problem?
I was able to replicate this by running the customer's marketwall on my player.  I'll share the details in the card.

**Comment by PatrickA-RiseVision** [comment]
@stulees I can't find the card for this to share the marketwall details on.  Where can I share them?

**Comment by stulees** [comment]
@PatrickA-RiseVision Can put them [here](https://trello.com/c/8advCBrQ/7714-issue-84-image-component-plays-default-image-immediately-before-presentations-are-swapped-2), thanks

**Comment by stulees** [comment]
@PatrickA-RiseVision Closed with #85
